top_srcdir   = /home/sh/rca_httpd/httpd/httpd-2.4.49
top_builddir = /home/sh/rca_httpd/httpd/httpd-2.4.49
srcdir       = /home/sh/rca_httpd/httpd/httpd-2.4.49/server/mpm/event
builddir     = /home/sh/rca_httpd/httpd/httpd-2.4.49/server/mpm/event
VPATH        = /home/sh/rca_httpd/httpd/httpd-2.4.49/server/mpm/event
include $(top_srcdir)/build/special.mk
