top_srcdir   = /home/sh/rca_httpd/httpd/httpd-2.4.49
top_builddir = /home/sh/rca_httpd/httpd/httpd-2.4.49
srcdir       = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/core
builddir     = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/core
VPATH        = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/core

include $(top_srcdir)/build/special.mk

