top_srcdir   = /home/sh/rca_httpd/httpd/httpd-2.4.49
top_builddir = /home/sh/rca_httpd/httpd/httpd-2.4.49
srcdir       = /home/sh/rca_httpd/httpd/httpd-2.4.49/server/mpm
builddir     = /home/sh/rca_httpd/httpd/httpd-2.4.49/server/mpm
VPATH        = /home/sh/rca_httpd/httpd/httpd-2.4.49/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
