top_srcdir   = /home/sh/rca_httpd/httpd/httpd-2.4.49
top_builddir = /home/sh/rca_httpd/httpd/httpd-2.4.49
srcdir       = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules
builddir     = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules
VPATH        = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

