top_srcdir   = /home/sh/rca_httpd/httpd/httpd-2.4.49
top_builddir = /home/sh/rca_httpd/httpd/httpd-2.4.49
srcdir       = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/echo
builddir     = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/echo
VPATH        = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/echo

include $(top_srcdir)/build/special.mk

