top_srcdir   = /home/sh/rca_httpd/httpd/httpd-2.4.49
top_builddir = /home/sh/rca_httpd/httpd/httpd-2.4.49
srcdir       = /home/sh/rca_httpd/httpd/httpd-2.4.49/os
builddir     = /home/sh/rca_httpd/httpd/httpd-2.4.49/os
VPATH        = /home/sh/rca_httpd/httpd/httpd-2.4.49/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
