top_srcdir   = /home/sh/rca_httpd/httpd/httpd-2.4.49
top_builddir = /home/sh/rca_httpd/httpd/httpd-2.4.49
srcdir       = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/cache
builddir     = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/cache
VPATH        = /home/sh/rca_httpd/httpd/httpd-2.4.49/modules/cache

include $(top_srcdir)/build/special.mk

